-- Generated by scripts/generate-supabase-seed.cjs from assets/data/menu.js.
-- Source SHA-256: 7b59e8270cfd3949b96a4f7b0e2456b149bab3e9f1f13a83140115683d82346e
-- Do not edit this file manually.

begin;

insert into public.categories (name, slug, description, sort_order, is_active)
values
  ('Breakfast', 'breakfast', null, 0, true),
  ('Burger', 'burger', null, 1, true),
  ('Pizza', 'pizza', null, 2, true),
  ('Wrap', 'wrap', null, 3, true),
  ('Chicken', 'chicken', null, 4, true),
  ('Juice', 'juice', null, 5, true),
  ('Shakes', 'shakes', null, 6, true),
  ('Seasonal Juice', 'seasonal-juice', null, 7, true),
  ('Hot Drinks', 'hot-drinks', null, 8, true),
  ('Soft Drinks', 'soft-drinks', null, 9, true)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

with seed_items (name, slug, category_slug, description, price, image_url, is_available, is_featured, sort_order) as (
  values
  ('Egg Sandwich', 'egg-sandwich', 'breakfast', null, 580.00, '/assets/images/menu/breakfast.jpg', true, false, 0),
  ('Scrambled Egg', 'scrambled-egg', 'breakfast', null, 680.00, '/assets/images/menu/breakfast.jpg', true, false, 1),
  ('Omelette', 'omelette', 'breakfast', null, 580.00, '/assets/images/menu/breakfast.jpg', true, false, 2),
  ('Vegetable Sandwich', 'vegetable-sandwich', 'breakfast', null, 550.00, '/assets/images/menu/breakfast.jpg', true, false, 3),
  ('Tuna Sandwich', 'tuna-sandwich', 'breakfast', null, 880.00, '/assets/images/menu/breakfast.jpg', true, false, 4),
  ('Club Sandwich', 'club-sandwich', 'breakfast', null, 880.00, '/assets/images/menu/breakfast.jpg', true, false, 5),
  ('Pan Cake', 'pan-cake', 'breakfast', null, 500.00, '/assets/images/menu/breakfast.jpg', true, false, 6),
  ('Chechebsa with Black', 'chechebsa-with-black', 'breakfast', null, 580.00, '/assets/images/menu/breakfast.jpg', true, false, 7),
  ('Chechebsa with White', 'chechebsa-with-white', 'breakfast', null, 580.00, '/assets/images/menu/breakfast.jpg', true, false, 8),
  ('Toast Bread with Egg', 'toast-bread-with-egg', 'breakfast', null, 450.00, '/assets/images/menu/breakfast.jpg', true, false, 9),
  ('Special Fetira', 'special-fetira', 'breakfast', null, 550.00, '/assets/images/menu/breakfast.jpg', true, false, 10),
  ('Normal Fetira', 'normal-fetira', 'breakfast', null, 450.00, '/assets/images/menu/breakfast.jpg', true, false, 11),
  ('Tuna Extra', 'tuna-extra', 'breakfast', null, 130.00, '/assets/images/menu/breakfast.jpg', true, false, 12),
  ('Fish Cotelet', 'fish-cotelet', 'breakfast', null, 998.00, '/assets/images/menu/breakfast.jpg', true, false, 13),
  ('Fish Gulash', 'fish-gulash', 'breakfast', null, 998.00, '/assets/images/menu/breakfast.jpg', true, false, 14),
  ('Fish Finger', 'fish-finger', 'breakfast', null, 998.00, '/assets/images/menu/breakfast.jpg', true, false, 15),
  ('Double Burger', 'double-burger', 'burger', 'Meat, tomato, onion, cheese, salad and mayonnaise.', 920.00, '/assets/images/menu/burger.jpg', true, false, 16),
  ('Cheese Burger', 'cheese-burger', 'burger', 'Meat, tomato, onion, salad and cheese.', 880.00, '/assets/images/menu/burger.jpg', true, false, 17),
  ('Beef Burger', 'beef-burger', 'burger', 'Meat, onion, tomato, salad and mayonnaise.', 820.00, '/assets/images/menu/burger.jpg', true, false, 18),
  ('Mini Special', 'mini-special', 'burger', 'Meat, tomato, lettuce, cheese, egg and mayonnaise.', 895.00, '/assets/images/menu/burger.jpg', true, false, 19),
  ('Fasting Double Burger', 'fasting-double-burger', 'burger', null, 820.00, '/assets/images/menu/burger.jpg', true, false, 20),
  ('Takeaway Box', 'takeaway-box', 'burger', null, 95.00, '/assets/images/menu/burger.jpg', true, false, 21),
  ('Extra Egg/Cheese/Beef', 'extra-egg-cheese-beef', 'burger', null, 130.00, '/assets/images/menu/burger.jpg', true, false, 22),
  ('Pommy Special Burger', 'pommy-special-burger', 'burger', 'Meat, egg, mayonnaise, chicken and beef slice.', 989.00, '/assets/images/menu/burger.jpg', true, true, 23),
  ('Pommy Chicken Special Burger', 'pommy-chicken-special-burger', 'burger', 'Double chicken, egg, mayonnaise, cheese, salad, onion and tomato.', 1250.00, '/assets/images/menu/burger.jpg', true, true, 24),
  ('Pommy Special Pizza', 'pommy-special-pizza', 'pizza', 'Tomato sauce, mozzarella cheese, meat, egg, olive, mushroom, beef slice, pesto and ricotta cheese.', 1155.00, '/assets/images/menu/hot-drink.jpg', true, true, 25),
  ('Beef Meat Lover Pizza', 'beef-meat-lover-pizza', 'pizza', 'Tomato sauce, mozzarella cheese, beef, pepper, onion and oregano.', 1100.00, '/assets/images/menu/hot-drink.jpg', true, false, 26),
  ('Chicken Pizza', 'chicken-pizza', 'pizza', 'Tomato sauce, mozzarella cheese, chicken, onion, pepper and oregano.', 1125.00, '/assets/images/menu/hot-drink.jpg', true, false, 27),
  ('Margarita Pizza', 'margarita-pizza', 'pizza', 'Tomato sauce, cheese and oregano.', 800.00, '/assets/images/menu/hot-drink.jpg', true, false, 28),
  ('Pizzala Pizza', 'pizzala-pizza', 'pizza', null, 998.00, '/assets/images/menu/hot-drink.jpg', true, false, 29),
  ('Olive Pizza', 'olive-pizza', 'pizza', 'Tomato sauce, cheese, olive and oregano.', 998.00, '/assets/images/menu/hot-drink.jpg', true, false, 30),
  ('Tuna Pizza', 'tuna-pizza', 'pizza', 'Tomato sauce, mozzarella cheese, tuna, pepper and onion.', 998.00, '/assets/images/menu/hot-drink.jpg', true, false, 31),
  ('Calzoni Pizza', 'calzoni-pizza', 'pizza', 'Tomato sauce, cheese, oregano, beef slice and sliced cheese.', 900.00, '/assets/images/menu/hot-drink.jpg', true, false, 32),
  ('Fasting Special Pizza', 'fasting-special-pizza', 'pizza', 'Tomato, tuna, onion, pepper and olive.', 920.00, '/assets/images/menu/hot-drink.jpg', true, false, 33),
  ('Vegetable Pizza', 'vegetable-pizza', 'pizza', null, 880.00, '/assets/images/menu/hot-drink.jpg', true, false, 34),
  ('Tuna Fasting Pizza', 'tuna-fasting-pizza', 'pizza', null, 900.00, '/assets/images/menu/hot-drink.jpg', true, false, 35),
  ('Pizza Takeaway Box', 'pizza-takeaway-box', 'pizza', null, 95.00, '/assets/images/menu/hot-drink.jpg', true, false, 36),
  ('Chicken BBQ Pizza', 'chicken-bbq-pizza', 'pizza', null, 1190.00, '/assets/images/menu/hot-drink.jpg', true, true, 37),
  ('Chicken Wrap', 'chicken-wrap', 'wrap', null, 1100.00, '/assets/images/menu/chicken.jpg', true, false, 38),
  ('Tuna Wrap', 'tuna-wrap', 'wrap', null, 998.00, '/assets/images/menu/chicken.jpg', true, false, 39),
  ('French Fries', 'french-fries', 'wrap', null, 400.00, '/assets/images/menu/chicken.jpg', true, false, 40),
  ('Vegetable Wrap', 'vegetable-wrap', 'wrap', null, 800.00, '/assets/images/menu/chicken.jpg', true, false, 41),
  ('Half Grill Chicken', 'half-grill-chicken', 'chicken', null, 1998.00, '/assets/images/menu/chicken.jpg', true, false, 42),
  ('Chicken Drum Stick', 'chicken-drum-stick', 'chicken', null, 1150.00, '/assets/images/menu/chicken.jpg', true, false, 43),
  ('Chicken Crispy', 'chicken-crispy', 'chicken', null, 1150.00, '/assets/images/menu/chicken.jpg', true, false, 44),
  ('Chicken Wing', 'chicken-wing', 'chicken', null, 1150.00, '/assets/images/menu/chicken.jpg', true, false, 45),
  ('Chicken Bowl', 'chicken-bowl', 'chicken', null, 1150.00, '/assets/images/menu/chicken.jpg', true, false, 46),
  ('Lasagne', 'lasagne', 'chicken', null, 1150.00, '/assets/images/menu/chicken.jpg', true, false, 47),
  ('Chicken Breast', 'chicken-breast', 'chicken', null, 1150.00, '/assets/images/menu/chicken.jpg', true, false, 48),
  ('Chicken Cutlets', 'chicken-cutlets', 'chicken', null, 1150.00, '/assets/images/menu/chicken.jpg', true, false, 49),
  ('Vegetable Rice', 'vegetable-rice', 'chicken', null, 850.00, '/assets/images/menu/chicken.jpg', true, false, 50),
  ('Rice with Meat', 'rice-with-meat', 'chicken', null, 950.00, '/assets/images/menu/chicken.jpg', true, false, 51),
  ('Rice with Chicken / Tuna', 'rice-with-chicken-tuna', 'chicken', null, 950.00, '/assets/images/menu/chicken.jpg', true, false, 52),
  ('Roasted Orange Chicken (Full)', 'roasted-orange-chicken-full', 'chicken', null, 2650.00, '/assets/images/menu/chicken.jpg', true, false, 53),
  ('Roasted Grilled Chicken (Half)', 'roasted-grilled-chicken-half', 'chicken', null, 1300.00, '/assets/images/menu/chicken.jpg', true, false, 54),
  ('Roasted Orange Chicken (Half)', 'roasted-orange-chicken-half', 'chicken', null, 1350.00, '/assets/images/menu/chicken.jpg', true, false, 55),
  ('Pommy Special Smoothie', 'pommy-special-smoothie', 'juice', 'Strawberry, avocado, papaya, mango, banana and orange.', 295.00, '/assets/images/menu/shake.jpg', true, false, 56),
  ('Mocha Pommy', 'mocha-pommy', 'juice', 'Mango, papaya, banana, milk and chocolate syrup.', 286.00, '/assets/images/menu/shake.jpg', true, false, 57),
  ('Mixed', 'mixed-juice', 'juice', 'Strawberry, avocado, papaya, milk and chocolate.', 286.00, '/assets/images/menu/shake.jpg', true, false, 58),
  ('Pommy Special Juice with TA', 'pommy-special-juice-with-ta', 'juice', null, 345.00, '/assets/images/menu/shake.jpg', true, false, 59),
  ('Strawberry Shake', 'strawberry-shake', 'shakes', null, 295.00, '/assets/images/menu/shake.jpg', true, false, 60),
  ('Chocolate Milk Shake', 'chocolate-milk-shake', 'shakes', null, 295.00, '/assets/images/menu/shake.jpg', true, false, 61),
  ('Banana Milk Shake', 'banana-milk-shake', 'shakes', null, 295.00, '/assets/images/menu/shake.jpg', true, false, 62),
  ('Milk Shake', 'milk-shake', 'shakes', 'Mango, banana, milk and chocolate syrup.', 295.00, '/assets/images/menu/shake.jpg', true, false, 63),
  ('Fruit Salad', 'fruit-salad', 'shakes', null, 300.00, '/assets/images/menu/shake.jpg', true, false, 64),
  ('Orange Juice', 'orange-juice', 'seasonal-juice', null, 320.00, '/assets/images/menu/drink.jpg', true, false, 65),
  ('Mango Juice', 'mango-juice', 'seasonal-juice', null, 295.00, '/assets/images/menu/drink.jpg', true, false, 66),
  ('Papaya Juice', 'papaya-juice', 'seasonal-juice', null, 286.00, '/assets/images/menu/drink.jpg', true, false, 67),
  ('Avocado Juice', 'avocado-juice', 'seasonal-juice', null, 286.00, '/assets/images/menu/drink.jpg', true, false, 68),
  ('Watermelon Juice', 'watermelon-juice', 'seasonal-juice', null, 295.00, '/assets/images/menu/drink.jpg', true, false, 69),
  ('Juice Cup', 'juice-cup', 'seasonal-juice', null, 40.00, '/assets/images/menu/drink.jpg', true, false, 70),
  ('Ananas Juice', 'ananas-juice', 'seasonal-juice', null, 295.00, '/assets/images/menu/drink.jpg', true, false, 71),
  ('Half Half Juice', 'half-half-juice', 'seasonal-juice', null, 285.00, '/assets/images/menu/drink.jpg', true, false, 72),
  ('Tea', 'tea', 'hot-drinks', null, 58.87, '/assets/images/menu/drink.jpg', true, false, 73),
  ('Tea Espresso', 'tea-espresso', 'hot-drinks', null, 104.00, '/assets/images/menu/drink.jpg', true, false, 74),
  ('Macchiato', 'macchiato', 'hot-drinks', null, 109.87, '/assets/images/menu/drink.jpg', true, false, 75),
  ('Fasting Macchiato', 'fasting-macchiato', 'hot-drinks', null, 150.87, '/assets/images/menu/drink.jpg', true, false, 76),
  ('Cafe Latte / Milk', 'cafe-latte-milk', 'hot-drinks', null, 133.05, '/assets/images/menu/drink.jpg', true, false, 77),
  ('Cappuccino', 'cappuccino', 'hot-drinks', null, 161.01, '/assets/images/menu/drink.jpg', true, false, 78),
  ('Flavored Tea', 'flavored-tea', 'hot-drinks', null, 110.65, '/assets/images/menu/drink.jpg', true, false, 79),
  ('Peanut Tea', 'peanut-tea', 'hot-drinks', null, 133.50, '/assets/images/menu/drink.jpg', true, false, 80),
  ('Special Tea', 'special-tea', 'hot-drinks', null, 161.35, '/assets/images/menu/drink.jpg', true, false, 81),
  ('Coffee', 'coffee', 'hot-drinks', null, 120.00, '/assets/images/menu/drink.jpg', true, false, 82),
  ('Espresso', 'espresso', 'hot-drinks', null, 110.00, '/assets/images/menu/drink.jpg', true, false, 83),
  ('Peanut', 'peanut', 'hot-drinks', null, 1330.00, '/assets/images/menu/drink.jpg', true, false, 84),
  ('Keshir', 'keshir', 'hot-drinks', null, 98.00, '/assets/images/menu/drink.jpg', true, false, 85),
  ('Hot Drinks Takeaway', 'hot-drinks-takeaway', 'hot-drinks', null, 40.87, '/assets/images/menu/drink.jpg', true, false, 86),
  ('Double Peanut Tea', 'double-peanut-tea', 'hot-drinks', null, 200.00, '/assets/images/menu/drink.jpg', true, false, 87),
  ('Double Fasting Macchiato', 'double-fasting-macchiato', 'hot-drinks', null, 200.00, '/assets/images/menu/drink.jpg', true, false, 88),
  ('Double Tea', 'double-tea', 'hot-drinks', null, 80.00, '/assets/images/menu/drink.jpg', true, false, 89),
  ('Tea with Lemon', 'tea-with-lemon', 'hot-drinks', null, 70.00, '/assets/images/menu/drink.jpg', true, false, 90),
  ('Hot Chocolate', 'hot-chocolate', 'hot-drinks', null, 207.00, '/assets/images/menu/drink.jpg', true, false, 91),
  ('Double Macchiato', 'double-macchiato', 'hot-drinks', null, 230.00, '/assets/images/menu/drink.jpg', true, false, 92),
  ('Soft Drinks', 'soft-drinks', 'soft-drinks', null, 75.00, '/assets/images/menu/drink.jpg', true, false, 93),
  ('Bottled Soft Drinks 300 ml', 'bottled-soft-drinks-300ml', 'soft-drinks', null, 100.00, '/assets/images/menu/drink.jpg', true, false, 94),
  ('Ambo Flavour / Water', 'ambo-flavour-water', 'soft-drinks', null, 100.00, '/assets/images/menu/drink.jpg', true, false, 95),
  ('Soft Drinks 500 ml', 'soft-drinks-500ml', 'soft-drinks', null, 100.00, '/assets/images/menu/drink.jpg', true, false, 96),
  ('Soft Drink 1 L', 'soft-drink-1l', 'soft-drinks', null, 75.00, '/assets/images/menu/drink.jpg', true, false, 97),
  ('Water 1 L', 'water-1l', 'soft-drinks', null, 60.00, '/assets/images/menu/drink.jpg', true, false, 98),
  ('Pepsi', 'pepsi', 'soft-drinks', null, 75.00, '/assets/images/menu/drink.jpg', true, false, 99),
  ('Water 1/2 L', 'water-half-litre', 'soft-drinks', null, 50.00, '/assets/images/menu/drink.jpg', true, false, 100)
)
insert into public.menu_items (
  name, slug, category_id, description, price, image_url, is_available, is_featured, sort_order
)
select
  seed.name, seed.slug, category.id, seed.description, seed.price, seed.image_url,
  seed.is_available, seed.is_featured, seed.sort_order
from seed_items seed
join public.categories category on category.slug = seed.category_slug
on conflict (slug) do update set
  name = excluded.name,
  category_id = excluded.category_id,
  description = excluded.description,
  price = excluded.price,
  image_url = excluded.image_url,
  is_available = excluded.is_available,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order;

do $$
begin
  if (select count(*) from public.categories) <> 10 then
    raise exception 'Seed validation failed: expected exactly 10 categories';
  end if;
  if (select count(*) from public.menu_items) <> 101 then
    raise exception 'Seed validation failed: expected exactly 101 menu items';
  end if;
  if (select count(*) from public.menu_items where is_featured) <> 4 then
    raise exception 'Seed validation failed: expected exactly 4 canonical featured flags';
  end if;
end;
$$;

commit;
